services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./:/usr/src/app
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    container_name: todo-frontend-dev